<?php

namespace AppBundle\Repository;

/**
 * EquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTipo($tipo) {
        return $this->createQueryBuilder('e')
            ->where('e.tipo = :tipo')
            ->orderBy('e.nombre', 'ASC')
            ->setParameter('tipo', $tipo)
            ->getQuery()
            ->getResult();
    }
}
