<?php

namespace AppBundle\Repository;

/**
 * PaginaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaginaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPublicPaginasOrderByPosicion() {
        return $this->createQueryBuilder('p')
            ->where('p.posicion > :posicion')
            ->orderBy('p.posicion', 'ASC')
            ->setParameter('posicion', 0)
            ->getQuery()
            ->getResult();
    }
}
